name: Test Workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache CMake
      uses: actions/cache@v2
      with:
        path: ~/.cmake  # Ścieżka do katalogu, który chcesz zachować w cache
        key: cmake-ubuntu  # Unikalny klucz dla cache
        restore-keys: |
          cmake-  # Lista kluczy do przywracania cache

    - name: Set up CMake
      run: sudo apt-get -y install cmake
     
    - name: Build Google Test
      run: |
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build
        cd build
        cmake ..
        make

    - name: Build project
      run: |
        rm -rdf build
        mkdir -p build
        cd build
        cmake -DCMAKE_SOURCE_DIR=${GITHUB_WORKSPACE} ..
        make ut

    - name: Run tests
      run: |
        cd build
        ctest
