name: Test Workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache CMake
      uses: actions/cache@v2
      with:
        path: ~/.cmake  # Ścieżka do katalogu, który chcesz zachować w cache
        key: cmake-ubuntu  # Unikalny klucz dla cache
        restore-keys: |
          cmake-  # Lista kluczy do przywracania cache

    - name: Set up CMake
      run: sudo apt-get -y install cmake

    - name: Build project
      run: |
        mkdir -p build
        cd build
        cmake ${GITHUB_WORKSPACE}
        make tst

    - name: Run tests
      run: |
        cd build
        ctest
